//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZzukBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZzukBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] beep {
            get {
                object obj = ResourceManager.GetObject("beep", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character: {0}.
        /// </summary>
        internal static string CharacterName {
            get {
                return ResourceManager.GetString("CharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths: {0}.
        /// </summary>
        internal static string Deaths {
            get {
                return ResourceManager.GetString("Deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnects: {0}.
        /// </summary>
        internal static string Disconnects {
            get {
                return ResourceManager.GetString("Disconnects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duel requests: {0}.
        /// </summary>
        internal static string DuelRequests {
            get {
                return ResourceManager.GetString("DuelRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Fasm_NET {
            get {
                object obj = ResourceManager.GetObject("Fasm_NET", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FastCall {
            get {
                object obj = ResourceManager.GetObject("FastCall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild invites: {0}.
        /// </summary>
        internal static string GuildInvites {
            get {
                return ResourceManager.GetString("GuildInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRC Bots will connect to irc.quakenet.org:6667
        ///A tutorial about how to use IRC can be found in the forums
        ///Choose a random generated channel-name 
        ///which cant be guessed by a third party
        ///Anyone who is able to join your channel can also interact with the bot
        ///
        ///Commands:
        ///!help
        ///!say MESSAGE
        ///!guild MESSAGE
        ///!party MESSAGE
        ///!whisper RECIEVER MESSAGE
        ///!lua CODE.
        /// </summary>
        internal static string IrcDescription {
            get {
                return ResourceManager.GetString("IrcDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items looted: {0}.
        /// </summary>
        internal static string ItemsLooted {
            get {
                return ResourceManager.GetString("ItemsLooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LevelUps: {0}.
        /// </summary>
        internal static string LevelUps {
            get {
                return ResourceManager.GetString("LevelUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Loader {
            get {
                object obj = ResourceManager.GetObject("Loader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set user mode for &apos;{0}&apos;..
        /// </summary>
        internal static string MessageCannotSetUserMode {
            get {
                return ResourceManager.GetString("MessageCannotSetUserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel type &apos;{0}&apos; sent by the server is invalid..
        /// </summary>
        internal static string MessageInvalidChannelType {
            get {
                return ResourceManager.GetString("MessageInvalidChannelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message command &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageInvalidCommand {
            get {
                return ResourceManager.GetString("MessageInvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command definition &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageInvalidCommandDefinition {
            get {
                return ResourceManager.GetString("MessageInvalidCommandDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command &apos;{0}&apos; was not recognised..
        /// </summary>
        internal static string MessageInvalidMessageCommand {
            get {
                return ResourceManager.GetString("MessageInvalidMessageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The non-trailing parameter &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageInvalidMiddleParameter {
            get {
                return ResourceManager.GetString("MessageInvalidMiddleParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified nick name is invalid..
        /// </summary>
        internal static string MessageInvalidNickName {
            get {
                return ResourceManager.GetString("MessageInvalidNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified password is invalid..
        /// </summary>
        internal static string MessageInvalidPassword {
            get {
                return ResourceManager.GetString("MessageInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message prefix &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageInvalidPrefix {
            get {
                return ResourceManager.GetString("MessageInvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quoted character &apos;{0}&apos; was not recognised..
        /// </summary>
        internal static string MessageInvalidQuotedChar {
            get {
                return ResourceManager.GetString("MessageInvalidQuotedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified real name is invalid..
        /// </summary>
        internal static string MessageInvalidRealName {
            get {
                return ResourceManager.GetString("MessageInvalidRealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object provided for registration info is of an unknown type..
        /// </summary>
        internal static string MessageInvalidRegistrationInfoObject {
            get {
                return ResourceManager.GetString("MessageInvalidRegistrationInfoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration info for a service must have a valid nick name and description..
        /// </summary>
        internal static string MessageInvalidServiceRegistrationInfo {
            get {
                return ResourceManager.GetString("MessageInvalidServiceRegistrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source &apos;{0}&apos; of the message was not recognised as either a server or user..
        /// </summary>
        internal static string MessageInvalidSource {
            get {
                return ResourceManager.GetString("MessageInvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message tag &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageInvalidTag {
            get {
                return ResourceManager.GetString("MessageInvalidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A target name may not contain any &apos;,&apos; character..
        /// </summary>
        internal static string MessageInvalidTargetName {
            get {
                return ResourceManager.GetString("MessageInvalidTargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trailing parameter &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageInvalidTrailingParameter {
            get {
                return ResourceManager.GetString("MessageInvalidTrailingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL scheme &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string MessageInvalidUrlScheme {
            get {
                return ResourceManager.GetString("MessageInvalidUrlScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user mode is invalid..
        /// </summary>
        internal static string MessageInvalidUserMode {
            get {
                return ResourceManager.GetString("MessageInvalidUserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name is invalid..
        /// </summary>
        internal static string MessageInvalidUserName {
            get {
                return ResourceManager.GetString("MessageInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration info for a user must have a valid nick name and user name..
        /// </summary>
        internal static string MessageInvalidUserRegistrationInfo {
            get {
                return ResourceManager.GetString("MessageInvalidUserRegistrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ISUPPORT message sent by the server contains an invalid PREFIX parameter..
        /// </summary>
        internal static string MessageISupportPrefixInvalid {
            get {
                return ResourceManager.GetString("MessageISupportPrefixInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough mode parameters were specified for the given modes..
        /// </summary>
        internal static string MessageNotEnoughModeParameters {
            get {
                return ResourceManager.GetString("MessageNotEnoughModeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host name &apos;{0}&apos; does not resolve to a valid IP address..
        /// </summary>
        internal static string MessageNoValidAddress {
            get {
                return ResourceManager.GetString("MessageNoValidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of a raw message must not exceed {0} characters..
        /// </summary>
        internal static string MessageRawMessageTooLong {
            get {
                return ResourceManager.GetString("MessageRawMessageTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message source &apos;{0}&apos; is not a user..
        /// </summary>
        internal static string MessageSourceNotUser {
            get {
                return ResourceManager.GetString("MessageSourceNotUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the given target mask &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string MessageTargetMaskInvalidType {
            get {
                return ResourceManager.GetString("MessageTargetMaskInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target mask must be contain at least two characters..
        /// </summary>
        internal static string MessageTargetMaskTooShort {
            get {
                return ResourceManager.GetString("MessageTargetMaskTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more than 3 mode parameters may be sent per message..
        /// </summary>
        internal static string MessageTooManyModeParameters {
            get {
                return ResourceManager.GetString("MessageTooManyModeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more than 15 command parameters may be specified..
        /// </summary>
        internal static string MessageTooManyParams {
            get {
                return ResourceManager.GetString("MessageTooManyParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be an empty string.
        /// </summary>
        internal static string MessageValueCannotBeEmptyString {
            get {
                return ResourceManager.GetString("MessageValueCannotBeEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wow.exe
        ///ntdll.dll
        ///kernel32.dll
        ///kernelbase.dll
        ///advapi32.dll
        ///msvcrt.dll
        ///sechost.dll
        ///rpcrt4.dll
        ///sspicli.dll
        ///cryptbase.dll
        ///comctl32.dll
        ///gdi32.dll
        ///user32.dll
        ///lpk.dll
        ///usp10.dll
        ///shell32.dll
        ///shlwapi.dll
        ///wsock32.dll
        ///ws2_32.dll
        ///nsi.dll
        ///opengl32.dll
        ///glu32.dll
        ///ddraw.dll
        ///dciman32.dll
        ///setupapi.dll
        ///cfgmgr32.dll
        ///oleaut32.dll
        ///ole32.dll
        ///devobj.dll
        ///dwmapi.dll
        ///imm32.dll
        ///msctf.dll
        ///divxdecoder.dll
        ///winmm.dll
        ///fmod.dll
        ///msacm32.dll
        ///wininet.dll
        ///api-ms-win-downlevel-user32-l1-1-0.dll
        ///api-ms-win-do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModulesOfWoW {
            get {
                return ResourceManager.GetString("ModulesOfWoW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party invites: {0}.
        /// </summary>
        internal static string PartyInvites {
            get {
                return ResourceManager.GetString("PartyInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PathFinder {
            get {
                object obj = ResourceManager.GetObject("PathFinder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running since {0} minutes.
        /// </summary>
        internal static string RunningSince {
            get {
                return ResourceManager.GetString("RunningSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades requested: {0}.
        /// </summary>
        internal static string TradeRequests {
            get {
                return ResourceManager.GetString("TradeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units killed: {0}.
        /// </summary>
        internal static string UnitsKilled {
            get {
                return ResourceManager.GetString("UnitsKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP gained: {0}.
        /// </summary>
        internal static string XpGained {
            get {
                return ResourceManager.GetString("XpGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP/hour: {0}.
        /// </summary>
        internal static string XpHour {
            get {
                return ResourceManager.GetString("XpHour", resourceCulture);
            }
        }
    }
}
